name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      # TODO: add a build step here
      - name: Build project
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: build
          workingDirectory: ./fuoco-core-api/libs/core
          all: 'true'

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "fuoco-appdev-core-api"
